"""Generate a standalone Blender Python script that imports the exported GLB,
sets up a sun, camera framing the model, and a Cycles render. Run with:

    blender --background --python <name>_blender.py
"""

from __future__ import annotations

from pathlib import Path

_TEMPLATE = '''"""Auto-generated by mapgen. Builds and renders the scene '{basename}'.

Usage:
    blender --background --python {script_name}
    # or open Blender and run this from the Scripting tab.
"""
import bpy
import os
import math

HERE = os.path.dirname(os.path.abspath(__file__))
GLB = os.path.join(HERE, "{glb_name}")
OUT = os.path.join(HERE, "{basename}_render.png")

# --- clean slate ---
bpy.ops.wm.read_factory_settings(use_empty=True)

# --- import the generated model ---
bpy.ops.import_scene.gltf(filepath=GLB)

# --- frame everything ---
objs = [o for o in bpy.context.scene.objects if o.type == "MESH"]
if objs:
    minc = [min(o.bound_box[i][a] + o.location[a] for o in objs for i in range(8)) for a in range(3)]
    maxc = [max(o.bound_box[i][a] + o.location[a] for o in objs for i in range(8)) for a in range(3)]
    center = [(minc[a] + maxc[a]) / 2 for a in range(3)]
    span = max(maxc[a] - minc[a] for a in range(3)) or 1.0
else:
    center, span = [0, 0, 0], 10.0

# --- sun ---
sun_data = bpy.data.lights.new("Sun", type="SUN")
sun_data.energy = 3.0
sun = bpy.data.objects.new("Sun", sun_data)
sun.rotation_euler = (math.radians(50), 0, math.radians(35))
bpy.context.collection.objects.link(sun)

# --- camera (3/4 aerial) ---
cam_data = bpy.data.cameras.new("Camera")
cam = bpy.data.objects.new("Camera", cam_data)
cam.location = (center[0] + span * 0.9, center[1] - span * 0.9, center[2] + span * 0.8)
direction = (
    center[0] - cam.location[0],
    center[1] - cam.location[1],
    center[2] - cam.location[2],
)
cam.rotation_euler = (
    math.atan2(math.hypot(direction[0], direction[1]), -direction[2]),
    0,
    math.atan2(direction[1], direction[0]) + math.pi / 2,
)
bpy.context.collection.objects.link(cam)
bpy.context.scene.camera = cam

# --- render settings (Cycles) ---
scene = bpy.context.scene
scene.render.engine = "CYCLES"
try:
    scene.cycles.samples = 128
except Exception:
    pass
scene.render.resolution_x = 1600
scene.render.resolution_y = 1000
scene.render.filepath = OUT

world = bpy.data.worlds.new("World")
world.use_nodes = True
bg = world.node_tree.nodes.get("Background")
if bg:
    bg.inputs[0].default_value = (0.55, 0.7, 0.95, 1.0)
    bg.inputs[1].default_value = 1.0
scene.world = world

if bpy.app.background:
    bpy.ops.render.render(write_still=True)
    print("mapgen: render written to", OUT)
'''


def write_blender_script(path: Path, glb_name: str, basename: str) -> None:
    path.write_text(
        _TEMPLATE.format(
            basename=basename,
            glb_name=glb_name,
            script_name=path.name,
        ),
        encoding="utf-8",
    )
